apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easy-ordering.fullname" . }}-account
  labels:
    {{- include "easy-ordering.labels" . | nindent 4 }}
    easy-ordering.app: "account"
data:
  application.yaml: |
    {{- toYaml .Values.account.config | nindent 4 }}