apiVersion: v1
kind: Service
metadata:
  name: {{ include "easy-ordering.fullname" . }}-order
  labels:
    {{- include "easy-ordering.labels" . | nindent 4 }}
    easy-ordering.app: "order"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.order.config.server.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.order.config.dubbo.protocol.port }}
      targetPort: http
      protocol: TCP
      name: dubbo
  selector:
    {{- include "easy-ordering.selectorLabels" . | nindent 4 }}
    easy-ordering.app: "order"
