apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easy-ordering.fullname" . }}-order
  labels:
    {{- include "easy-ordering.labels" . | nindent 4 }}
    easy-ordering.app: "order"
data:
  application.yaml: |
    {{- toYaml .Values.order.config | nindent 4 }}